SET-527 Address Vulnerabilities in Spring Web and OKIO Library
partior-3p/tessera pull request #17
Opened 2024-06-21 06:27 UTC by john-sobrepena-partior

## PR Description
This PR is to fix multiple vulnerabilities in Tessera. More details below

## Fixed Issue(s)
- Fix vulnerability (CVE-2023-3635) detected in com.squareup.okio:okio:1.15 library in `hashicorp-key-vault` modile. More details about the vulnerability here https://avd.aquasec.com/nvd/cve-2023-3635 (VULN-3698)
- Fix vulnerability (CVE-2016-1000027) detected in spring-web library (https://avd.aquasec.com/nvd/cve-2016-1000027). spring-vault-code was upgraded from 5.3.33 to 6.0.2 (VULN-12362)

## Documentation
- Documentation is not required to be updated

2024-06-21 06:39 UTC, krishnan-narayanan-partior approved these changes, later dismissed

2024-06-21 07:23 UTC, rodion-lim-partior submitted a review, later dismissed

2024-06-24 01:40 UTC, rodion-lim-partior approved these changes

2024-06-24 01:40 UTC, rodion-lim-partior requested changes
One of the pipeline build is failing, analyze dependencies

2024-06-26 06:41 UTC, john-sobrepena-partior commented
> One of the pipeline build is failing, analyze dependencies

This is now resolved. Pipeline CI tests all successful

2024-06-26 06:54 UTC, rodion-lim-partior approved these changes

2024-06-26 07:05 UTC, frank-lim-partior approved these changes

2024-06-26 07:05 UTC, merged